baseurl = "https://example.com"
languageCode = "en"
title = "Prakhar Srivastav | Blogs"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/PrakharSrivastav\">Prakhar Srivastav</a> 2019"
disqusShortname = ""
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Prakhar Srivastav" # Author full name
authorEmail = "srivprakhar@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = ""
github = "PrakharSrivastav"
email = "srivprakhar@gmail.com"
linkedin = "ribice"
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

#[params.social.config]
platforms = ["github","email","linkedin"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true